version: '3'
services:
  app:
    build: .
    image: robsdudeson/landbnb
    restart: always
    command: sh -c "wait-for-it db:3306 -- bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - "db:dbhost"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    expose:
      - "3306"

volumes:
  dbdata:
